In [1]:
#2-1 用字串建構一個Unicode編碼位置串列
symbols = '$&@!%*'
codes = []
for symbol in symbols:
    codes.append(ord(symbol))

print("2-1:",codes)


#2-2 用字串建構一個Unicode編碼位置串列，只用兩行程式
symbols = '$&@!%*'
codes = [ord(symbol) for symbol in symbols]
print("2-2:",codes)

"""
ord() 函数是 chr() 函数（对于8位的ASCII字符串或unichr()函数（对于Unicode对象）
的配对函数，它以一个字符（长度为1的字符串）作为参数，返回对应的 ASCII 数值，
或者 Unicode 数值，如果所给的 Unicode 字符超出了你的 Python 定义范围，
则会引发一个 TypeError 的异常。
"""

2-1: [36, 38, 64, 33, 37, 42]
2-2: [36, 38, 64, 33, 37, 42]


In [5]:
#2-3listcomp與map/filter組合建構的同一串列
symbols = '$&@!%*'
beyond_ascii = [ord(s) for s in symbols if ord(s) > 27]
print(beyond_ascii)

beyond_ascii =list(filter(lambda c: c >27,map(ord,symbols)))
print(beyond_ascii)




[36, 38, 64, 33, 37, 42]


[36, 38, 64, 33, 37, 42]

In [6]:
#2-4 使用串列生成式來作笛卡爾乘積
colors = ['black','white']
sizes = ['S','M','L']
tshirts = [(color,size) for color in colors for size in sizes]
print(tshirts)

for color in colors:
    for size in sizes:
        print((color,size))
        
tshirts = [(color,size) for size in sizes for color in colors]
tshirts

[('black', 'S'), ('black', 'M'), ('black', 'L'), ('white', 'S'), ('white', 'M'), ('white', 'L')]
('black', 'S')
('black', 'M')
('black', 'L')
('white', 'S')
('white', 'M')
('white', 'L')


[('black', 'S'),
 ('white', 'S'),
 ('black', 'M'),
 ('white', 'M'),
 ('black', 'L'),
 ('white', 'L')]

In [9]:
#2-5 以產生器表達式來初始化tuple與陣列
colors = ['black','white']
sizes = ['S','M','L']
symbols = '$&@!%*'
tuple(ord(symbol) for symbol in symbols)
import array
array.array('I',(ord(symbol)for symbol in symbols))

#2-6以產生氣做迪卡爾乘績
for tshirt in ('%s %s'%(c,s) for c in colors for s in sizes):
    print(tshirt)
    
#2-7將tuple當作紀錄
lax_coordinates = (33.9425,-118.408056)
city = ('Tokyo',2003,32450,0.66,8014)
travel_id = [('USA','31195855'),('BRA','CE342567'),('ESP','XDA205856')]
for passort in sorted(travel_id):
    print('%s %s' %passort)
    
for country, _ in travel_id:
    print(country)

black S
black M
black L
white S
white M
white L
BRA CE342567
ESP XDA205856
USA 31195855
USA
BRA
ESP


In [18]:
#拆解Tuple
lax_coordinates = (33.9425,-118.408056)
city = ('Tokyo',2003,32450,0.66,8014)

latitude,longitude = lax_coordinates 
print(latitude,longitude)

divmod(20,8)

t = (20,8)
divmod(*t)

quotient,remainder = divmod(*t)

quotient
remainder

33.9425 -118.408056


4

In [2]:
import os
_,filename = os.path.split('/home/luciano/.ssh/idrsa.pub')
filename

#用*來捕捉項目
rangeA = range(5)
rangeA
a,b, *rest = range(5) 
print(a,b,rest)


'idrsa.pub'

In [9]:
#用*來捕捉項目
rangeA = range(5)
rangeA
a,b, *rest = range(5) 
print(a,b,rest)


0 1 [2, 3, 4]


In [13]:
#2-8拆解嵌套式tuple,來取得經度
metro_areas = [
    ('Tokyo','JP',36.933,(35,139)),
    ('Delhi NCR','IN',21.935,(28,77)),
    ('Mexico City','MX',20,(19,-99)),
    ('New York','US',20,(40,-74)),
    ('Sao Paulo','BR',19,(-23,-46)),   
]

print('{:15} | {:^9} |{:^9}'.format('','lat','long'))
fmt = '{:15} | {:9.4f} | {:9.4f}'
for name,cc,pop,(latitude,longitude) in metro_areas:
    if longitude <=0:
        print(fmt.format(name,latitude,longitude))

                |    lat    |  long   
Mexico City     |   19.0000 |  -99.0000
New York        |   40.0000 |  -74.0000
Sao Paulo       |  -23.0000 |  -46.0000


In [1]:
#2-9定義並使用具名tuple型態
from collections import namedtuple
City = namedtuple('City','name country population coordinates')
tokyo = City('Tokyo','JP','36',(35,139))
tokyo
tokyo.population
tokyo.coordinates
tokyo[3]

#具tuple屬性與方法
print(City._fields)
LatLong = namedtuple('LatLong','lat long')
delhi_data = ('Delhi NCR','IN',21.935,LatLong(28,77))
delhi = City._make(delhi_data)
print(delhi._asdict())

for key,value in delhi._asdict().items():
    print(key,':',value)

A = (1,2,3,4,5,6)
type(A)    
#dir(A)

('name', 'country', 'population', 'coordinates')
OrderedDict([('name', 'Delhi NCR'), ('country', 'IN'), ('population', 21.935), ('coordinates', LatLong(lat=28, long=77))])
name : Delhi NCR
country : IN
population : 21.935
coordinates : LatLong(lat=28, long=77)


tuple

In [24]:
#2-12 一個可用來表示井字棋盤的串列,裡面有3個長度為三的串列

board = [['_']*3 for i in range(3)]
board

board[1][2] = 'x'
print(board)


#2-13 一個串列,他的三個內部串列全部都參考到同一串列
white_board = [['_']*3]*3
#print(white_board)
white_board[1][0] = 'o'
print(white_board)



[['_', '_', '_'], ['_', '_', 'x'], ['_', '_', '_']]
[['o', '_', '_'], ['o', '_', '_'], ['o', '_', '_']]


['', '', '']

In [28]:
#2-15 意外的結果:項目t2被改變,且發出一個例外
t = (1,2,[30,40])

t[2] += [50,60]


TypeError: 'tuple' object does not support item assignment

In [30]:
#2-16 
#Disassembler for python bytecode
import dis
dis.dis('s[a] += b')

  1           0 LOAD_NAME                0 (s)
              2 LOAD_NAME                1 (a)
              4 DUP_TOP_TWO
              6 BINARY_SUBSCR
              8 LOAD_NAME                2 (b)
             10 INPLACE_ADD
             12 ROT_THREE
             14 STORE_SUBSCR
             16 LOAD_CONST               0 (None)
             18 RETURN_VALUE


In [10]:
#2-20建立,儲存與載入一個大型的浮點陣列

from array import array 
from random import random

#'d': C Type-> double  python -> float
floats = array('d',(random() for i in range(10*7)))

print(floats)

floats[-1]

fp = open('floats.bin','wb')

#numpy.ndarray.tofile:write array to a file as text or binary
floats.tofile(fp)
fp.close()

#建立一個double空陣列
floats2 = array('d')
fp = open('floats.bin','rb')

#construct an array from data in a text or binary file.
#從二進位檔案讀取70個數字
floats2.fromfile(fp,10*7)
fp.close()

print(floats2[-1])

floats == floats2


array('d', [0.9763889940181576, 0.31666371244448344, 0.5511629578482418, 0.3418302580482031, 0.2703139532832196, 0.11240350175173408, 0.265024614959818, 0.6413188441818886, 0.6069007693019767, 0.8637981407762206, 0.11066978644913661, 0.4169294415687025, 0.6060870451853372, 0.2950692947760559, 0.9713219297774776, 0.036893942673466684, 0.3493978431315614, 0.30958813735722956, 0.7778272250706171, 0.21683816367137565, 0.8817428447205637, 0.10878983233318607, 0.6082963376320426, 0.6945213611284882, 0.056901989418635335, 0.26431899594978436, 0.9219072170905521, 0.7135379332798307, 0.613750243735458, 0.5767431400396846, 0.2092283264512631, 0.014641463982596248, 0.15899851799299614, 0.4342980401394937, 0.43170678310772237, 0.514597909895135, 0.1541994537213317, 0.7316231024693721, 0.6200210323933301, 0.37025631944144655, 0.5122750445268485, 0.7564637710994978, 0.9373531363130732, 0.4669251075644487, 0.9281891166571152, 0.46244516878110775, 0.24326489894891423, 0.058613167573682845, 0.919076851

True

In [20]:
#記憶體資訊
import array

#2-21 藉由更改一個陣列項目的其中一個byte,來改變它的值

numbers = array.array('h',[-2,-1,0,1,2])

memv = memoryview(numbers)
print(memv)

print(len(memv))

memv[0]

memv_oct = memv.cast('B')

#Convert the array to an ordinary list with the same items.
print(memv_oct.tolist())

memv_oct[5] = 4
print(memv_oct[0])

numbers


5
[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]
254


array('h', [-2, -1, 1024, 1, 2])

In [8]:
#numpy.ndarray的基本列,欄操作

import numpy
a = numpy.arange(12)
a
type(a)
a.shape
a.shape = 3,4
print(a)

a.transpose()


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [24]:
#使用deque
#雙端佇列（deque，全名double-ended queue）是一種具有佇列和堆疊性質的抽象資料類型。雙端佇列中的元素可以從兩端彈出，插入和刪除操作限定在佇列的兩邊進行。

from collections import deque
dq = deque(range(10),maxlen=10)
dq
help(dq.rotate)
dq.rotate(3)
dq

dq.rotate(-4)
dq

dq.appendleft(-1)

dq
dq.extend([11,22,33])

dq

dq.extendleft([10,20,30,40])
dq





Help on built-in function rotate:

rotate(...) method of collections.deque instance
    Rotate the deque n steps to the right (default n=1).  If n is negative, rotates left.



deque([40, 30, 20, 10, 3, 4, 5, 6, 7, 8])